# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."prometheus-runner" = {
    image = "docker.io/gitea/act_runner:nightly";
    environmentFiles = [
      "${config.sops.secrets."forgejo-runner/environment".path}"
    ];
    volumes = [
      "/home/server/olympus-nixos/modules/nyx/services/forgejo-runner/config.yaml:/config.yaml:rw"
      "/home/server/olympus-nixos/modules/nyx/services/forgejo-runner/data:/data:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=runner"
      "--network=prometheus_default"
    ];
  };
  systemd.services."docker-prometheus-runner" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-prometheus_default.service"
    ];
    requires = [
      "docker-network-prometheus_default.service"
    ];
    partOf = [
      "docker-compose-prometheus-root.target"
    ];
    wantedBy = [
      "docker-compose-prometheus-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-prometheus_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f prometheus_default";
    };
    script = ''
      docker network inspect prometheus_default || docker network create prometheus_default
    '';
    partOf = [ "docker-compose-prometheus-root.target" ];
    wantedBy = [ "docker-compose-prometheus-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-prometheus-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
