{ inputs, self, ... }: {
  flake.nixosModules.automation = { inputs, ... }: {
    imports = [
      inputs.self.nixosModules.docker
      inputs.self.nixosModules.homeAssistant
      inputs.self.nixosModules.printing
    ];
  };

  flake.nixosModules.printing = { pkgs, ... }: {
    services.printing = {
      enable = true;
      drivers = with pkgs; [
        cups-filters
        cups-browsed
        canon-cups-ufr2
      ];
    };

    hardware.sane.enable = true;
  };

  flake.nixosModules.docker = { inputs, ... }: {
    virtualisation.docker = {
      enable = true;
      daemon.settings = {
        experimental = true;
        default-address-pools = [
          {
            base = "172.30.0.0/16";
            size = 24;
          }
        ];
      };
    };

    environment.systemPackages = [
      inputs.compose2nix.packages.x86_64-linux.default
    ];

    users.users.server.extraGroups = [ "docker" ];
  };

  flake.nixosModules.homeAssistant = { config, ... }: {
    imports = [ inputs.self.nixosModules.govee2mqtt inputs.self.nixosModules.mosquitto ];

    services.home-assistant = {
      enable = true;
      extraComponents = [
        "analytics"
        "google_translate"
        "met"
        "radio_browser"
        "shopping_list"
        "isal"
        "samsungtv"
        "govee_light_local"
        "mqtt"
        "wake_on_lan"
      ];
      config = {

        "wake_on_lan" = [
          {
            alias = "Wake 'athena-windows'";
            switch = {
              platform = "wake_on_lan";
              mac = "D8-43-AE-54-2A-7E";
              name = "athena-windows";
            };
          }
        ];

        "automation sunset_lights" = [
          {
            alias = "Turn on lights at sunset";
            triggers = {
              trigger = "numeric_state";
              entity_id = "sun.sun";
              attribute = "elevation";
              below = "-3.0";
            };
            actions = {
              action = "light.turn_on";
              entity_id = "all";
            };
          }
        ];
        "automation sunrise_lights" = [
          {
            alias = "Turn off lights at sunrise";
            triggers = {
              trigger = "numeric_state";
              entity_id = "sun.sun";
              attribute = "elevation";
              above = "-3.0";
            };
            actions = {
              action = "light.turn_off";
              entity_id = "all";
            };
          }
        ];
        "automation ui" = "!include automations.yaml";
        "scene ui" = "!include scenes.yaml";
        "script ui" = "!include scripts.yaml";

        "lights" = [
          {
            unique_id = "light.all_lights";
            platform = "group";
            entities = [
              "light.h6004_20de"
              "light.h6004_c2be"
              "light.h8072_796f"
            ];
          }
        ];

        homeassistant = {
          internal_url = "http://172.17.100.1:8123";
          external_url = "https://home.puppygirls.net";
        };

        http = {
          use_x_forwarded_for = true;
          trusted_proxies = [
            "127.0.0.1"
            "::1"
          ];
        };

        default_config = { };
      };
    };

    systemd.tmpfiles.rules = [
      "f ${config.services.home-assistant.configDir}/automations.yaml 0644 hass hass"
      "f ${config.services.home-assistant.configDir}/scenes.yaml 0644 hass hass"
      "f ${config.services.home-assistant.configDir}/scripts.yaml 0644 hass hass"
    ];
  };

  flake.nixosModules.mosquitto = { ... }: {
    services.mosquitto = {
      enable = true;
      listeners = [
        {
          acl = [ "pattern readwrite #" ];
          omitPasswordAuth = true;
          settings.allow_anonymous = true;
        }
      ];
    };
  };

  flake.nixosModules.govee2mqtt = { pkgs, lib, ... }: {
    # Auto-generated by compose2nix

    # Runtime
    virtualisation.docker = {
      enable = true;
      autoPrune.enable = true;
    };
    virtualisation.oci-containers.backend = "docker";

    # Containers
    virtualisation.oci-containers.containers."govee2mqtt" = {
      image = "ghcr.io/wez/govee2mqtt:latest";
      environment = {
        #"GOVEE_API_KEY" = "cum";
        #"GOVEE_EMAIL" = "urmom";
        "GOVEE_MQTT_HOST" = "localhost";
        "GOVEE_MQTT_PORT" = "1883";
        #"GOVEE_PASSWORD" = "cum";
        "GOVEE_TEMPERATURE_SCALE" = "C";
        "RUST_LOG_STYLE" = "always";
        "TZ" = "America/New_York";
        "GOVEE_LAN_NO_MULTICAST" = "false";
        "GOVEE_LAN_BROADCAST_ALL" = "true";
        #"GOVEE_LAN_BROADCAST_GLOBAL" = "true";
      };
      volumes = [
        "/media/hdd1/docker/govee2mqtt/data:/data:rw"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network=host"
      ];
    };
    systemd.services."docker-govee2mqtt" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      partOf = [
        "docker-compose-govee2mqtt-root.target"
      ];
      wantedBy = [
        "docker-compose-govee2mqtt-root.target"
      ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-govee2mqtt-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
