{ ... }:
{
  imports = [
    ./power.nix
    ./hardenedKernel.nix
    ./services/media/jellyfin/default.nix
    ./services/media/freshrss.nix
    ./services/remote-builder.nix
    ./services/ntfy.nix
    ./services/mollysocket.nix
    ./services/qbittorrent.nix
    ./services/ssh-tunnel.nix
    ./services/syncthing.nix
    ../global/functions.nix
    #./services/samba.nix
    ./nvidia.nix
    ./packages.nix
    #./services/frigate.nix
    ./services/navidrome.nix
    ./services/audiobookshelf.nix
    ./services/yt-dlp/default.nix
    ./services/networking/default.nix
    ./services/attic.nix
    ./services/printing.nix
    ./services/forgejo-runner/forgejo-runner.nix
    #../xfce/default.nix
    #./services/x2go.nix
    #./services/dawarich.nix
    ./services/game-servers/crafty-controller.nix
    #./services/piped-backend.nix
    ./services/game-servers/minecraft/default.nix
    ./services/game-servers/factorio.nix
    ./services/homeassistant/default.nix
    ./services/copyparty.nix
    ./services/docker.nix
    ./services/mosquitto.nix
    ../global/power/disable-shutdown.nix
    #./services/web/default.nix
    ./services/samba/samba.nix
    ./services/actual-finance/actual-server.nix
    ./services/immich.nix
    #./services/ollama.nix
  ];
}
