name: Update Flake Inputs

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  update:
    runs-on: nixos-x86_64-linux
    steps:
    - uses: actions/checkout@v4

    - name: Update flake inputs
      uses: Mic92/update-flake-inputs-gitea@main
      with:
        forgejo-token: ${{ secrets.FORGEJO_TOKEN }}
        git-author-name: "prometheus"
        git-committer-name: "prometheus"