{ pkgs, config, util, lib, ... }:
let
  moondeckBuddy = pkgs.callPackage ../packages/moondeckbuddy.nix { };

  # Runs headless (NO_GUI=true) by default; moondeckbuddy-gui-session.service
  # flips it to GUI mode while a graphical session is active, since pairing
  # with the MoonDeck client is disabled in headless mode. Mirrors the units
  # generated by upstream's own `moondeck-buddy --enable-autostart`.
  moondeckBuddyStart = pkgs.writeShellScript "moondeckbuddy-start" ''
    NO_GUI="''${MOONDECKBUDDY_NO_GUI:-true}" ${moondeckBuddy}/bin/moondeck-buddy
  '';
  moondeckBuddyGuiSession = pkgs.writeShellScript "moondeckbuddy-gui-session" ''
    sleep infinity &
    PID=$!
    trap "kill $PID" INT TERM
    systemctl --user set-environment MOONDECKBUDDY_NO_GUI=false
    systemctl --user try-restart moondeckbuddy.service
    wait
    systemctl --user unset-environment MOONDECKBUDDY_NO_GUI
    systemctl --user try-restart moondeckbuddy.service
  '';

  virtualDisplayEdidHex =
    "00ffffffffffff004c2dc07245464c30"
    + "1d200104b54628783a4ed5ae4e45aa27"
    + "0e505425cf0081c0810081809500a9c0"
    + "b300714f010108e80030f2705a80b058"
    + "8a00b9882100001e000000fd081ea51e"
    + "759c000a202020202020000000fc004f"
    + "6479737365792047370a2020000000ff"
    + "00484e54543730303034330a20200173"
    + "020326f048615f101f3f040376230907"
    + "0783010000e305c000e60605018b5a00"
    + "e5018b849079565e00a0a0a029503020"
    + "3500b9882100001a6fc200a0a0a05550"
    + "30203500b9882100001a023a80187138"
    + "2d40582c4500b9882100001e00000000"
    + "00000000000000000000000000000000"
    + "000000000000000000000000000000bf";

  virtualDisplayEdidHexFile = pkgs.writeText "virtualDisplay-edid.hex" virtualDisplayEdidHex;

  virtualDisplayEdidScript = pkgs.writeText "make-edid.py" ''
    import sys
    with open(sys.argv[1]) as f:
        hex_str = f.read().strip()
    with open(sys.argv[2], "wb") as f:
        f.write(bytes.fromhex(hex_str))
  '';

  virtualDisplayEdidPkg = pkgs.runCommand "samsung-g7-virtual-display-edid" { } ''
    mkdir -p $out/lib/firmware/edid
    ${pkgs.python3}/bin/python3 ${virtualDisplayEdidScript} \
      ${virtualDisplayEdidHexFile} \
      $out/lib/firmware/edid/virtualDisplay.bin
  '';
in
{
  services.sunshine = {
    enable = true;
    autoStart = true;
    capSysAdmin = true;
    openFirewall = true;
    applications = {
      env = {
        PATH = "$(PATH):$(HOME)/.local/bin";
      };
      apps = [
        {
          name = "Steam Big Picture";
          detached = [
            "setsid steam steam://open/bigpicture"
          ];
          prep-cmd = [
            {
              do = "";
              undo = "setsid steam steam://close/bigpicture";
            }
          ];
          image-path = "steam.png";
          exclude-global-prep-cmd = "false";
          auto-detach = "true";
        }
        {
          name = "MoonDeckStream";
          cmd = "${moondeckBuddy}/bin/moondeck-buddy --exec MoonDeckStream";
          auto-detach = "false";
        }
      ];
    };
    settings = {
      sunshine_name = "athena-nixos";
      notify_pree_releases = "disabled";
      system_tray = "enabled";
      controller = "enabled";
      gamepad = "auto";
      back_button_timeout = "3000";
      stream_audio = "enabled";
      virtual_sink = "Steam Streaming Speakers";
      adapter_name = "/dev/dri/renderD128";
      output_name = "DP-1";
      max_bitrate = "0";
      address_family = "both";
      lan_encryption_mode = "0";
      wan_encrpytion_mode = "2";
      global_prep_cmd = builtins.toJSON [
        {
          "do" = "wlr-randr --output DP-1 --on --mode 3840x2160@120";
          "undo" = "wlr-randr --output DP-1 --off";
        }
        {
          "do" = "wlr-randr --output DP-2 --off";
          "undo" = "wlr-randr --output DP-2 --on";
        }
        {
          "do" = "wlr-randr --output HDMI-A-1 --off";
          "undo" = "wlr-randr --output HDMI-A-1 --on";
        }
      ];
    };
  };

  networking.firewall.allowedTCPPorts = [
    47984
    47989
    47990
    48010
    59999
  ];

  users.users.foxtrot = {
    extraGroups = [ "uinput" ];
  };

  hardware.display.outputs."DP-1".mode = "e";
  hardware.display.outputs."DP-1".edid = "virtualDisplay.bin";

  hardware.display.edid.packages = [ virtualDisplayEdidPkg ];

  sops.secrets."sunshine/password" = {
    owner = config.users.users.foxtrot.name;
  };

  systemd.user.services.sunshine.serviceConfig.ExecStartPre = [
    "${pkgs.writeShellScript "sunshine-set-creds" ''
      ${config.services.sunshine.package}/bin/sunshine \
        --creds foxtrot "$(cat ${config.sops.secrets."sunshine/password".path})"
    ''}"
  ];

  # Matches upstream's own systemd units (see `moondeck-buddy --enable-autostart`,
  # and https://github.com/FrogTheFrog/moondeck-buddy/wiki/Buddy-installation-guide).
  # Runs as user services (not system) so they start at login.
  systemd.user.services.moondeckbuddy = {
    description = "MoonDeck host companion";
    after = [ "default.target" ];
    wantedBy = [ "default.target" ];
    serviceConfig = {
      Type = "exec";
      ExecStart = "${moondeckBuddyStart}";
      Restart = "on-failure";
      RestartSec = 10;
      SuccessExitStatus = 143;
    };
  };

  # Switches moondeckbuddy.service to GUI mode (needed for MoonDeck pairing)
  # while a graphical session is running, reverting to headless on logout.
  systemd.user.services."moondeckbuddy-gui-session" = {
    description = "GUI session monitor for MoonDeckBuddy service";
    after = [ "xdg-desktop-autostart.target" ];
    partOf = [ "xdg-desktop-autostart.target" ];
    wantedBy = [ "xdg-desktop-autostart.target" ];
    serviceConfig = {
      Type = "exec";
      ExecStart = "${moondeckBuddyGuiSession}";
      Restart = "no";
    };
  };

  environment.systemPackages = with pkgs; [
    wlr-randr
  ];
}
