# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."govee2mqtt" = {
    image = "ghcr.io/wez/govee2mqtt:latest";
    environment = {
      #"GOVEE_API_KEY" = "cum";
      #"GOVEE_EMAIL" = "urmom";
      "GOVEE_MQTT_HOST" = "localhost";
      "GOVEE_MQTT_PORT" = "1883";
      #"GOVEE_PASSWORD" = "cum";
      "GOVEE_TEMPERATURE_SCALE" = "C";
      "RUST_LOG_STYLE" = "always";
      "TZ" = "America/New_York";
      "GOVEE_LAN_NO_MULTICAST" = "false";
      "GOVEE_LAN_BROADCAST_ALL" = "true";
      #"GOVEE_LAN_BROADCAST_GLOBAL" = "true";
    };
    volumes = [
      "/media/hdd1/docker/govee2mqtt/data:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."docker-govee2mqtt" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-govee2mqtt-root.target"
    ];
    wantedBy = [
      "docker-compose-govee2mqtt-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-govee2mqtt-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
