# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7fc9a9ab-823c-4584-9b3d-1d1507d4fdf5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7fc9a9ab-823c-4584-9b3d-1d1507d4fdf5".device = "/dev/disk/by-uuid/7fc9a9ab-823c-4584-9b3d-1d1507d4fdf5";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/746C-E970";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/media/ssd2linux" =
    { device = "/dev/disk/by-uuid/7b940d6c-f4c8-4768-9095-a646f8ef6cee";
      fsType = "xfs";
    };

  fileSystems."/media/extra" =
    { device = "/dev/disk/by-uuid/b898f79f-4dd3-4a24-ac2a-c05e9340e551";
      fsType = "ext4";
    };

  fileSystems."/media/plus" =
    { device = "/dev/disk/by-uuid/ff907343-1f1f-4bb4-ba6a-73b3e11454b4";
      fsType = "xfs";
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-54236609-4086-41ec-a07f-21d1ba3bd0fc"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
